GET http://localhost:3000/reservations
content-type: application/json

###

POST http://localhost:3000/reservations
content-type: application/json

{
  "startTime": "2022-03-02T14:00:00.000Z",
  "endTime": "2022-03-02T14:26:48.730Z"
}

###

DELETE http://localhost:3000/reservations/10